language: python
cache: pip
python:
  - "3.5"

env:
  global:
    - VERSION='3.1.2'
    - CIBW_BEFORE_BUILD='bash build-deps.sh'
    - CIBW_BUILD='cp35-* cp36-* cp37-*'
    - CIBW_SKIP='*-win32 *-manylinux1_i686'
    - CIBW_BUILD_VERBOSITY=0
    - CIBW_ENVIRONMENT_LINUX='CFLAGS="-std=c99"'
    - CIBW_ENVIRONMENT_MACOS='CC=clang CFLAGS="-std=c99"'
    - CIBW_TEST_REQUIRES='numpy==1.15.1 pytest pytest-astropy'
    - CIBW_TEST_COMMAND='pytest -W ignore $(dirname $(python -c "import astropy; print(astropy.__file__)"))'

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip3

install:
  - $PIP install cibuildwheel

script:
  # - wget -O- https://files.pythonhosted.org/packages/source/a/astropy/astropy-$VERSION.tar.gz | tar xz
  - wget -O- https://github.com/astropy/astropy/archive/v${VERSION}.tar.gz | tar xz
  - cp build-deps.sh astropy-$VERSION/
  - cd astropy-$VERSION
  - cibuildwheel --output-dir ../wheelhouse
  - cd ..
  - ls wheelhouse

deploy:
  provider: releases
  api_key:
    secure: bHKoAE9vX23kJ8sHT/U35EpNHasCxzDi0q3rzP8NvCIE3e4MbaAdwLNMltpLBwQO0vp5tOJOdSzoe7lqIoYqkKYh4oxQPKOWu6a5NWOzz6QHJyO95SsmF7psT23S86vLd4U424J9Xp9GbMks/o3v8t/sC+JAQI4HR7vzrwi1oLrRpmRVCbTRWjgbCfs8+3QPygqA5dOIpO4cO1PE35hbijZEt13nUtUFEu5ffl3UfGU48NxIbTmvv3pOTb+qr/p91UmbO+sHDuXDdIaKCD6to8nybBtw0vYzooa+2y8J/ZyEfrG69PR4hUlGdXSMGo6FXC7SHJ+ZazkmzwvusLTf6tm1BgKt5EVW+8I+izhoE93CVIaUi5s8YJzTZP/LwKn6YOXdyqSxhOotpgRURjOZJgb0Xm6mTnoRiMYH3mE1LhS/ovdyVl4doJjqTGz+kuHPOoK8D/EspIA04KO3V4OY7d1aznL3sG2ylj4JDUTViMjIuQL2S/fY4UeqiP29ZzOXCYBgdZ0s6AgB3ViwZ0pUHtX3mUO0L6Ha/lorUXtt9RrNmdFqjRgMDEC25irSNO5DmnHIq7XjHVuUwq1abTW425VkG/qz60yHptmqW9i14v2f7Oljv33kJqpY+AaTNaBXdz1CXvQiI8mcyT1Blmp5hvMYH16NMpNlP/c6QJIDmW8=
  skip_cleanup: true
  file_glob: true
  file: wheelhouse/*.whl
  on:
    repo: saimn/try-cibuildwheel
